name = "abi"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "104.16.0.0"
UUID = "a256c6ac-47a3-423f-9845-7a2fcfd2e72e"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
